version: 2.1

orbs:
  aws-sam-serverless: circleci/aws-sam-serverless@3.0
jobs:
  # test_my_api:
  #   docker:
  #     - image:
  #   steps:
  #     - run: go test ./...
  # build_app:
  #   executor: aws-sam-serverless/default
  #   steps:
  #     - checkout
  #     - aws-sam-serverless/install
  #     - run: sam build
workflows:
  build_and_deploy:
    jobs:
      # - aws-sam-serverless/deploy:
      #     context: aws-credentials-context
      #     name: deploy-staging
      #     s3-bucket: $AWS_ARTIFACT_BUCKET
      #     stack-name: staging-stack
      #     template: ./template.yaml
      # - test_my_api:
      #     requires:
      #       - deploy-staging
      # - build_app
      - aws-sam-serverless/deploy:
          name: deploy-production
          # requires:
          #   - test_my_api
          #   - build_app
          s3-bucket: hello-world-here
          stack-name: production-stack
          template: ./template.yaml
          build-dir: hello-world/
